### ISSUE TITLE
Maintainer URL should be updated

### ISSUE THREAD

**Issue by gfmaster** [prabirshrestha/synology-nomad#30]
First of all, thank you for the great package.

This is small, nitpicky thing...

maintainer_url in info.sh points to
maintainer_url="https://github.com/prabirshrestha/synology-nomad-package"

which should be
maintainer_url="https://github.com/prabirshrestha/synology-nomad"

**Comment by prabirshrestha** [comment]
fixed in https://github.com/prabirshrestha/synology-nomad/commit/a1119dba7fe2356d4f194c17b59c9bf5caa5ee22. New release should have this fixed I the spk file going forward.
